baseURL = "https://blog.mmaakkyyii.com/"
languageCode = "ja"
title = "mmaakkyyii site"
theme = ["ananke"]

hasCJKLanguage = true
summaryLength = 120


#enableRobotsTXT = true

[params]
    custom_css = ["/css/maki_css.css"]
    site_logo = "/image/icon.ico"
    favicon = "/image/icon.ico"
    siteStartYear = 2021

[social]
    twitter = "mmaakkyyii"
    githug = "mmaakkyyii"

[menu]
[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/'
weight = 100

[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 200

[[menu.main]]
name = 'Blog'
url = '/posts/'
weight = 300

[[menu.main]]
name = 'Tag'
url = '/tags/'
weight = 400

[[menu.main]]
name = 'Category'
url = '/categories/'
weight = 500

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true