baseURL = "http://mmaakkyyii.com/"
languageCode = "ja"
title = "mmaakkyyii site"
theme = ["ananke"]

hasCJKLanguage = true
summaryLength = 120

#staticDir = ["static"]

[params]
    custom_css = ["/css/maki_css.css"]
    site_logo = "/image/icon.ico"